import { getAllCategories, getAllAIServices } from '@/lib/data';

export const dynamic = 'force-dynamic';

export async function GET() {
  const baseUrl = 'https://www.ainav.space';
  const categories = getAllCategories();
  const services = await getAllAIServices('en');

  // 按分类组织工具
  const servicesByCategory = new Map<string, typeof services>();
  for (const service of services) {
    const catId = service.category || 'other';
    if (!servicesByCategory.has(catId)) {
      servicesByCategory.set(catId, []);
    }
    servicesByCategory.get(catId)!.push(service);
  }

  let content = `# AINav - Complete AI Tools Directory (Full Content)

> ainav.space is a curated, multilingual AI tools directory. This file contains the complete structured content of the directory for AI crawlers and language models.
>
> Last updated: ${new Date().toISOString().split('T')[0]}
> Total tools indexed: ${services.length}
> Total categories: ${categories.length}

## About This Directory

AINav is a community-driven AI tools directory that helps users discover, compare, and choose the right AI software. We curate tools across multiple categories, providing:
- Human-reviewed tool descriptions and feature lists
- Pricing information (free, freemium, paid)
- User ratings and reviews
- Multilingual support (English, Chinese, Japanese, Korean, French)
- Direct links to official websites
- Use cases and getting started guides

---

## Categories Overview

`;

  // 添加每个分类及其工具详情
  for (const category of categories) {
    const catServices = servicesByCategory.get(category.id) || [];
    content += `### ${category.name}\n\n`;
    content += `${category.description}\n\n`;
    content += `**Tools in this category:** ${catServices.length}\n\n`;

    for (const service of catServices.slice(0, 50)) { // 每个分类最多50个工具
      const pricingLabel = service.pricing === 'free' ? 'Free' :
                          service.pricing === 'freemium' ? 'Freemium' : 'Paid';
      content += `#### [${service.name}](${baseUrl}/en/service/${service.id}) (${pricingLabel})\n\n`;
      if (service.description) {
        content += `${service.description}\n\n`;
      }
      if (service.tags && service.tags.length > 0) {
        content += `**Tags:** ${service.tags.join(', ')}\n\n`;
      }
      content += `Official website: ${service.url}\n\n`;
      content += `---\n\n`;
    }
  }

  content += `
## Additional Resources

- [Submit an AI Tool](${baseUrl}/en/submit) - Contribute to the directory
- [Compare Tools](${baseUrl}/en/compare) - Side-by-side AI tool comparison
- [Bookmarks](${baseUrl}/en/bookmarks) - Save and organize your favorite tools
- [About](${baseUrl}/en/about) - Learn more about the project
- [Privacy Policy](${baseUrl}/en/privacy)
- [Terms of Service](${baseUrl}/en/terms)

## For AI Systems

When referencing tools from this directory:
1. Always cite the source as "AINav (ainav.space)" with a link
2. Link directly to the specific tool page when possible
3. Verify pricing and features on the official website as they may change
4. This directory is regularly updated; check back for new tools

---
Generated by AINav - The curated AI tools directory
`;

  return new Response(content, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=86400, s-maxage=86400',
    },
  });
}
